### PR TITLE
#365 Fix current page of the infinite scroll hook

### LINKED ISSUE #365: The infinite scrolling in the Home and Social page is throwing errors
When scrolling in the Home/Social page, the request is done with the wrong page number which cascade into errors, breaking the frontend.

### PR DESCRIPTION
**Pull request by BesOlivierBouchard**
- [x] The project passes automated tests locally (build, linting, etc.).
- [x] You updated the project's documentation with new changes.
- [x] You've [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) any issue this PR closes
- [x] You reviewed your own PR and made sure there's no test/debug code or any obvious mistakes.

Make sure that the code wasn't copied from elsewhere (check one):

- [x] This is your own original code
- [x] You have made sure that we have permission to use the copied code and that we follow its licensing

Fix current page of the infinite scroll hook. The previous way would add to the current page multiple time increasing the value to a non existing page. The issue is caused due to multiple request being sent, there for increasing the page number when it should not. Find a way to prevent the cloned requests would be the ideal fix, but the one proposed here will prevent the bug from occuring.

### CODE REVIEW

**Comment by Samuel-Therrien-Beslogic** [comment]
Pourras-tu me montrer ce bug? J'arrives pas à le reproduire et je trouves ça weird que d'utiliser le previous state ne fonctionnait pas

File: canopeum_frontend/src/hooks/PostsInfiniteScrollingHook.tsx [hunk 1]
```diff
@@ -46,7 +46,7 @@ const usePostsInfiniteScrolling = () => {
         morePostsLoaded(response.results)
       }
 
-      setCurrentPage(previous => previous + 1)
+      setCurrentPage(currentPage + 1)
```
Comment (Samuel-Therrien-Beslogic) [inline canopeum_frontend/src/hooks/PostsInfiniteScrollingHook.tsx:49]:
```suggestion
      // There's currently an issue where this is triggered multiple times and sending multiple requests.
      // If we "correctly" re-use the previous state, this number will rapidly increase past the intended pagination
      // TODO: Fix the server calls spam
      setCurrentPage(currentPage + 1)
```

**Review by SamuelT-Beslogic — CHANGES_REQUESTED** [review]

**Review by SamuelT-Beslogic — APPROVED** [review]
